name: pokemon_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  http: ^1.2.1
  provider: ^6.1.2
  get_it: ^7.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
